### ISSUE TITLE
Match-Rosters are not filled

### ISSUE THREAD

**Issue by Bart1909** [mautini/pubgjava#1]
If you get a Match by its Id, the MatchAttributes are filled fine.

But the MatchRelationships are not filled well.The Roster behind the MatchRelationships are only filled with Id and Type. Not with RosterAttributes and RosterRelationships.

I thinks, thats because these information is given back by the api below the "included"-Tree.
In this "included"-Tree the partitipants with its stats and the rosters are listed.

**Comment by mautini** [comment]
Hi,

This is the "normal" behaviour: the purpose of this lib is to reflect the PUBG API. 

As you mentioned, when you get the match from the matches endpoint you have just the type and the id in the bracket relationships (the same thing happens for all the endpoints, for example, you have just the match id in the bracket relationships for a player response).

If you want a better way to navigate in a match object, I recommend to use the pubg-java-utils artifact. You'll find the getRosters() method : https://github.com/mautini/pubgjava/blob/master/pubg-java-utils/src/main/java/com/github/mautini/pubgjava/MatchResponseUtils.java

**Comment by Bart1909** [comment]
Ah okay, this workes fine! Thanks!
