### ISSUE TITLE
Add rate limit support.

### ISSUE THREAD

**Issue by daniel-jirca** [mautini/pubgjava#3]
Hello!
As the PUBG API is limited to 10 requests per minute, it would be great if the SDK would support some kind of rate limiting functionality.
Or, at least, the ability to return the response headers which contain information about the limits in custom keys (including a date for reset):
```
X-Ratelimit-Limit →10
X-Ratelimit-Remaining →7
X-Ratelimit-Reset →1529052065
```
Thanks!

**Comment by mautini** [comment]
Hi, I didn't know these headers. I provided a way to access it : Use the methods 

`getRateLimitRemaining()
getRateLimit()
getRateLimitReset()`

in PubgClient and PubgClientAsync.

I hope it resolve your issue

**Comment by daniel-jirca** [comment]
Can you publish a built jar with these changes?
Thanks for the update!

**Comment by mautini** [comment]
Oh yes, I forgot. I'll do it today

Le lun. 30 juil. 2018 à 12:50, Daniel Jircă <notifications@github.com> a
écrit :

**Comment by mautini** [comment]
I did it just now. Please let me know if you have any issue.
