### ISSUE TITLE
matches SoloDuo

### ISSUE THREAD

**Issue by daniel-jirca** [mautini/pubgjava#5]
Hello!
The class [PlayerSeasonRelationships](https://github.com/mautini/pubgjava/blob/master/pubg-java/src/main/java/com/github/mautini/pubgjava/model/playerseason/PlayerSeasonRelationships.java) has a property named `matchesSoloDuo` which doesn't correspond to any of the match types returned by the PUBG API on the `/players/{id}/seasons/{seasonID}` endpoint.

I think that its getter method also returns `null` all the time, but didn't investigate any further.

**Comment by mautini** [comment]
It was a Typo. matchesSoloDuo should be matchesDuo. I fixed it and re-published the project. I also refactored the fields in this class to be much readable.
